name: Update Last Commit Date and Time in README

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Get the last commit date and time
      run: echo "LAST_COMMIT_DATETIME=$(git log -1 --format='%cd' --date=format:'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

    - name: Update README
      run: |
        LAST_COMMIT_DATETIME="![Último Commit](https://img.shields.io/badge/último_commit-${LAST_COMMIT_DATETIME}-blue.svg)"
        sed -i "/Último Commit:/c\### Último Commit:\n${LAST_COMMIT_DATETIME}" README.md

    - name: Commit changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add README.md
        git commit -m "Atualiza data e hora do último commit"
        git push
